[workspace]
members = ["crates/*", "examples/*"]

# Build dependencies with optimizations
[profile.dev.package."*"]
opt-level = 2

# Build dependencies with optimizations
[profile.release.package."*"]
opt-level = 2

[profile.release]
debug = true
