[package]
name = "rush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
haste = { path = "../../crates/haste" }
tikv-jemallocator = { version = "0.5.0", features = ["background_threads"] }
