[package]
name = "haste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
bytemuck = { version = "1.12.3", features = ["derive", "zeroable_maybe_uninit"] }
hashbrown = { version = "0.13.1", features = ["raw"] }
libc = "0.2.138"
crossbeam-deque = "0.8.2"
pollster = "0.2.5"
futures-lite = "1.12.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread"] }
smallvec = { version = "1.10.0", features = ["const_new", "union"] }
parking_lot_core = "0.9.7"

[dependencies.haste_macros]
path = "../haste_macros"

[[example]]
name = "rad"
path = "examples/rad.rs"
