[package]
name = "rad"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.6.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.haste]
path = "../../crates/haste"
